language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install

  #before_script:
  # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "chenxi"
  - git config user.email "joechen1024@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${TravisCI}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo-resource
env:
  global:
    - GH_REF: github.com/chenxihub/cherish.github.io.git
